/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUICHART.RoomRatio;
import BUS.ChiTietHoaDonBUS;
import GUICHART.piechart.ModelPieChart;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TuiLaZit
 */
public class RR extends javax.swing.JPanel {

    /**
     * Creates new form RR
     */
    CardLayout layout;
    public RR() {
        initComponents();
        DataTable();
        DataChart();
        layout = new CardLayout();
    }

    private ArrayList setData(){
        ChiTietHoaDonBUS data = new ChiTietHoaDonBUS();
        ArrayList<RoomRatioModel> list = data.RoomRatio();
        return list;
    }
    
    private void DataTable(){
        ArrayList<RoomRatioModel> list = setData();
        DefaultTableModel table = new DefaultTableModel();
        RRTable.setModel(table);
        table.addColumn("Loại Phòng");
        table.addColumn("Lượng Khách");
        for(int i=0;i<=list.size()-1;i++){
            RoomRatioModel d = list.get(i);
            table.addRow(new Object[]{d.getRType(),d.getRCount()});
        }
    }
    
    private void DataChart(){
        List<RoomRatioModel> list = setData();
        int index = 0;
        for(int i=0;i<=list.size()-1;i++){
            RoomRatioModel d = list.get(i);
            RRChart.addData(new ModelPieChart(d.getRType(), d.getRCount(), getColor(index++)));
        }
    }
    
    private Color getColor(int index){
        Color[] color = new Color[]{new Color(196,107,81),new Color(78,117,102),new Color(108,70,117),new Color(211,110,112),new Color(93,155,155),new Color(96,111,140)};
        return color[index];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RRChart = new GUICHART.piechart.PieChart();
        jScrollPane1 = new javax.swing.JScrollPane();
        RRTable = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 242, 197));

        RRTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RRTable.setRowHeight(57);
        jScrollPane1.setViewportView(RRTable);

        Refresh.setBackground(new java.awt.Color(0, 16, 31));
        Refresh.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Refresh.setForeground(new java.awt.Color(220, 242, 197));
        Refresh.setText("Làm mới");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RRChart, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Refresh))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refresh)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RRChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        RRChart.clearData();
        DataChart();
        DataTable();
    }//GEN-LAST:event_RefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUICHART.piechart.PieChart RRChart;
    private javax.swing.JTable RRTable;
    private javax.swing.JButton Refresh;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
