/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUICHART.RoomRatio;
import BUS.ChiTietHoaDonBUS;
import GUICHART.piechart.ModelPieChart;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TuiLaZit
 */
public class RR extends javax.swing.JPanel {

    /**
     * Creates new form RR
     */
    CardLayout layout;
    public RR() {
        initComponents();
        DataTable();
        DataChart();
        layout = new CardLayout();
    }

    private ArrayList setData(){
        ChiTietHoaDonBUS data = new ChiTietHoaDonBUS();
        ArrayList<RoomRatioModel> list = data.RoomRatio();
        return list;
    }
    
    private void DataTable(){
        ArrayList<RoomRatioModel> list = setData();
        DefaultTableModel table = new DefaultTableModel();
        RRTable.setModel(table);
        table.addColumn("Loại Phòng");
        table.addColumn("Lượng Khách");
        for(int i=0;i<=list.size()-1;i++){
            RoomRatioModel d = list.get(i);
            table.addRow(new Object[]{d.getRType(),d.getRCount()});
        }
    }
    
    private void DataChart(){
        List<RoomRatioModel> list = setData();
        int index = 0;
        for(int i=0;i<=list.size()-1;i++){
            RoomRatioModel d = list.get(i);
            RRChart.addData(new ModelPieChart(d.getRType(), d.getRCount(), getColor(index++)));
        }
    }
    
    private Color getColor(int index){
        Color[] color = new Color[]{new Color(196,107,81),new Color(78,117,102),new Color(108,70,117),new Color(211,110,112),new Color(93,155,155),new Color(96,111,140)};
        return color[index];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RRChart = new GUICHART.piechart.PieChart();
        jScrollPane1 = new javax.swing.JScrollPane();
        RRTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(220, 242, 197));

        RRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RRTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RRChart, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {RRChart, jScrollPane1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RRChart, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {RRChart, jScrollPane1});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUICHART.piechart.PieChart RRChart;
    private javax.swing.JTable RRTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
