/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

import BUS.NguoiDungBUS;

public class DangNhap extends javax.swing.JFrame {
    NguoiDungBUS nd=new NguoiDungBUS();
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        DangKyUI = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TaiKhoanUI = new javax.swing.JTextField();
        MatKhauUI = new javax.swing.JPasswordField();
        DangNhapUI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jButton1.setText("jButton1");

        DangKyUI.setText("Đăng Ký");
        DangKyUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangKyUIActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");

        jPanel1.setBackground(new java.awt.Color(220, 242, 197));
        jPanel1.setForeground(new java.awt.Color(0, 16, 31));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);
        jPanel1.add(TaiKhoanUI);
        TaiKhoanUI.setBounds(145, 71, 170, 30);
        jPanel1.add(MatKhauUI);
        MatKhauUI.setBounds(145, 127, 170, 30);

        DangNhapUI.setBackground(new java.awt.Color(220, 242, 197));
        DangNhapUI.setForeground(new java.awt.Color(0, 16, 31));
        DangNhapUI.setText("Đăng Nhập");
        DangNhapUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhapUIActionPerformed(evt);
            }
        });
        jPanel1.add(DangNhapUI);
        DangNhapUI.setBounds(140, 220, 110, 30);

        jLabel1.setForeground(new java.awt.Color(0, 16, 31));
        jLabel1.setText("Tài Khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 70, 60, 30);

        jLabel2.setForeground(new java.awt.Color(0, 16, 31));
        jLabel2.setText("Mật Khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 60, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 190, 400, 3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DangNhapUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhapUIActionPerformed
        // TODO add your handling code here:
        String TaiKhoan=TaiKhoanUI.getText();
        String MatKhau=new String(MatKhauUI.getPassword());
        
        StringBuilder tb= new StringBuilder();
        
        if(TaiKhoan.equals("")){
            tb.append("Tài Khoản Không Được Để Trống\n");
        }
        if(MatKhau.equals("")){
            tb.append("Mật Khẩu Không Được Để Trống\n");
        }
        if(tb.length()>0){
            JOptionPane.showMessageDialog(this,tb.toString(),"Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }if(nd.dangnhap(TaiKhoan, MatKhau)!=null){
            dispose();
            Menu.main(nd.dangnhap(TaiKhoan, MatKhau));
        }else if (TaiKhoan.equals("admin")&& MatKhau.equals("admin123")) {
            dispose();
            Menu.main("ADMIN");
        }else{
            JOptionPane.showMessageDialog(this, "Tài khoản/mật khẩu sai!!!","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_DangNhapUIActionPerformed

    private void DangKyUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangKyUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DangKyUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DangKyUI;
    private javax.swing.JButton DangNhapUI;
    private javax.swing.JPasswordField MatKhauUI;
    private javax.swing.JTextField TaiKhoanUI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
