/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Phat
 */
public class DichVu extends javax.swing.JPanel {

    /**
     * Creates new form DichVu
     */
    public DichVu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDichVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PanelTTDV = new javax.swing.JPanel();
        LabelMaDV = new javax.swing.JLabel();
        LabelTenDV = new javax.swing.JLabel();
        LabelGiaDV = new javax.swing.JLabel();
        TFMaDV = new javax.swing.JTextField();
        TFTenDV = new javax.swing.JTextField();
        TFGiaDV = new javax.swing.JTextField();
        ButtonThemDV = new javax.swing.JButton();
        ButtonXoaDV = new javax.swing.JButton();
        ButtonChinhSuaDV = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel1.setBackground(new java.awt.Color(220, 242, 197));
        jPanel1.setPreferredSize(new java.awt.Dimension(1720, 1080));

        BangDichVu.setBackground(new java.awt.Color(220, 242, 197));
        BangDichVu.setForeground(new java.awt.Color(0, 16, 31));
        BangDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BangDichVu);

        jLabel1.setBackground(new java.awt.Color(220, 242, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 16, 31));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng Dịch Vụ");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 16, 31))); // NOI18N

        PanelTTDV.setBackground(new java.awt.Color(220, 242, 197));
        PanelTTDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelMaDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelMaDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelMaDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaDV.setText("Mã Dịch Vụ");
        LabelMaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelTenDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelTenDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelTenDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTenDV.setText("Tên Dịch Vụ");
        LabelTenDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelGiaDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelGiaDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelGiaDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGiaDV.setText("Giá");
        LabelGiaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        TFMaDV.setBackground(new java.awt.Color(220, 242, 197));
        TFMaDV.setForeground(new java.awt.Color(0, 16, 31));

        TFTenDV.setBackground(new java.awt.Color(220, 242, 197));
        TFTenDV.setForeground(new java.awt.Color(0, 16, 31));

        TFGiaDV.setBackground(new java.awt.Color(220, 242, 197));
        TFGiaDV.setForeground(new java.awt.Color(0, 16, 31));

        ButtonThemDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonThemDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonThemDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonThemDV.setText("Thêm");
        ButtonThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThemDVActionPerformed(evt);
            }
        });

        ButtonXoaDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXoaDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXoaDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXoaDV.setText("Xóa");

        ButtonChinhSuaDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonChinhSuaDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonChinhSuaDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonChinhSuaDV.setText("Chỉnh Sửa");
        ButtonChinhSuaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChinhSuaDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTTDVLayout = new javax.swing.GroupLayout(PanelTTDV);
        PanelTTDV.setLayout(PanelTTDVLayout);
        PanelTTDVLayout.setHorizontalGroup(
            PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTTDVLayout.createSequentialGroup()
                .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTTDVLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(ButtonChinhSuaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTTDVLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTTDVLayout.createSequentialGroup()
                                .addComponent(LabelGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(TFGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTTDVLayout.createSequentialGroup()
                                .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTTDVLayout.createSequentialGroup()
                                .addComponent(LabelTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTTDVLayout.createSequentialGroup()
                                .addComponent(LabelMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        PanelTTDVLayout.setVerticalGroup(
            PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTTDVLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(PanelTTDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(ButtonChinhSuaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(PanelTTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PanelTTDV, jScrollPane1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PanelTTDV, jScrollPane1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThemDVActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ButtonThemDVActionPerformed

    private void ButtonChinhSuaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChinhSuaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonChinhSuaDVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDichVu;
    private javax.swing.JButton ButtonChinhSuaDV;
    private javax.swing.JButton ButtonThemDV;
    private javax.swing.JButton ButtonXoaDV;
    private javax.swing.JLabel LabelGiaDV;
    private javax.swing.JLabel LabelMaDV;
    private javax.swing.JLabel LabelTenDV;
    private javax.swing.JPanel PanelTTDV;
    private javax.swing.JTextField TFGiaDV;
    private javax.swing.JTextField TFMaDV;
    private javax.swing.JTextField TFTenDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
