/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phat
 */
public class DichVu extends javax.swing.JPanel {
    Menu menu;
    /**
     * Creates new form DichVu
     */
    public DichVu(Menu menu) {
        initComponents();
        this.menu=menu;
        
        DefaultTableModel table=new DefaultTableModel();
        BangDichVu.setModel(table);
        table.addColumn("Mã Dich Vụ");
        table.addColumn("Tên Dịch Vụ");
        table.addColumn("Giá");
        BangDichVu.getTableHeader().setResizingAllowed(false);
        BangDichVu.setColumnSelectionAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DichVuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDichVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonXN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LabelMaDV = new javax.swing.JLabel();
        LabelTenDV = new javax.swing.JLabel();
        LabelGiaDV = new javax.swing.JLabel();
        TFMaDV = new javax.swing.JTextField();
        TFTenDV = new javax.swing.JTextField();
        TFGiaDV = new javax.swing.JTextField();
        ButtonThemDV = new javax.swing.JButton();
        ButtonXoaDV = new javax.swing.JButton();
        ButtonChinhSuaDV = new javax.swing.JButton();
        ChiTietDV = new javax.swing.JLabel();
        ButtonThoat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1720, 1080));

        DichVuPanel.setBackground(new java.awt.Color(220, 242, 197));
        DichVuPanel.setMinimumSize(new java.awt.Dimension(1000, 1000));
        DichVuPanel.setPreferredSize(new java.awt.Dimension(1720, 1080));

        BangDichVu.setBackground(new java.awt.Color(220, 242, 197));
        BangDichVu.setForeground(new java.awt.Color(0, 16, 31));
        BangDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chọn", "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BangDichVu);
        if (BangDichVu.getColumnModel().getColumnCount() > 0) {
            BangDichVu.getColumnModel().getColumn(0).setMinWidth(0);
            BangDichVu.getColumnModel().getColumn(0).setMaxWidth(75);
        }

        jLabel1.setBackground(new java.awt.Color(220, 242, 197));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 16, 31));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng Dịch Vụ");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 16, 31))); // NOI18N

        ButtonXN.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXN.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXN.setText("Xác Nhận");

        jPanel1.setBackground(new java.awt.Color(220, 242, 197));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelMaDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelMaDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelMaDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMaDV.setText("Mã Dịch Vụ");
        LabelMaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelTenDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelTenDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelTenDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTenDV.setText("Tên Dịch Vụ");
        LabelTenDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        LabelGiaDV.setBackground(new java.awt.Color(220, 242, 197));
        LabelGiaDV.setForeground(new java.awt.Color(0, 16, 31));
        LabelGiaDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGiaDV.setText("Giá");
        LabelGiaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        TFMaDV.setBackground(new java.awt.Color(220, 242, 197));
        TFMaDV.setForeground(new java.awt.Color(0, 16, 31));

        TFTenDV.setBackground(new java.awt.Color(220, 242, 197));
        TFTenDV.setForeground(new java.awt.Color(0, 16, 31));

        TFGiaDV.setBackground(new java.awt.Color(220, 242, 197));
        TFGiaDV.setForeground(new java.awt.Color(0, 16, 31));

        ButtonThemDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonThemDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonThemDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonThemDV.setText("Thêm");

        ButtonXoaDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXoaDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXoaDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXoaDV.setText("Xóa");

        ButtonChinhSuaDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonChinhSuaDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonChinhSuaDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonChinhSuaDV.setText("Chỉnh Sửa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(LabelGiaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ButtonChinhSuaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelGiaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFGiaDV, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(ButtonChinhSuaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        ChiTietDV.setBackground(new java.awt.Color(220, 242, 197));
        ChiTietDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChiTietDV.setForeground(new java.awt.Color(0, 16, 31));
        ChiTietDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChiTietDV.setText("Chi Tiết Dịch Vụ");
        ChiTietDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));

        ButtonThoat.setBackground(new java.awt.Color(220, 242, 197));
        ButtonThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonThoat.setForeground(new java.awt.Color(0, 16, 31));
        ButtonThoat.setText("Thoát");
        ButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DichVuPanelLayout = new javax.swing.GroupLayout(DichVuPanel);
        DichVuPanel.setLayout(DichVuPanelLayout);
        DichVuPanelLayout.setHorizontalGroup(
            DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DichVuPanelLayout.createSequentialGroup()
                .addGroup(DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DichVuPanelLayout.createSequentialGroup()
                        .addGroup(DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DichVuPanelLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(ButtonXN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(ButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DichVuPanelLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DichVuPanelLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(388, 388, 388)
                        .addComponent(ChiTietDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(616, Short.MAX_VALUE))
        );
        DichVuPanelLayout.setVerticalGroup(
            DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DichVuPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChiTietDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DichVuPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DichVuPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(DichVuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonXN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DichVuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DichVuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDichVu;
    private javax.swing.JButton ButtonChinhSuaDV;
    private javax.swing.JButton ButtonThemDV;
    private javax.swing.JButton ButtonThoat;
    private javax.swing.JButton ButtonXN;
    private javax.swing.JButton ButtonXoaDV;
    private javax.swing.JLabel ChiTietDV;
    private javax.swing.JPanel DichVuPanel;
    private javax.swing.JLabel LabelGiaDV;
    private javax.swing.JLabel LabelMaDV;
    private javax.swing.JLabel LabelTenDV;
    private javax.swing.JTextField TFGiaDV;
    private javax.swing.JTextField TFMaDV;
    private javax.swing.JTextField TFTenDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
