/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import BUS.DichVuBUS;
import DTO.DichVuDTO;
import DTO.NguoiDung.NguoiDungDTO;
import DTO.Phong.PhongDTO;
import DTO.Phong.PhongThuongDTO;
import DTO.Phong.PhongVipDTO;

/**
 *
 * @author capij
 */
public class DSDichVu extends javax.swing.JPanel {
    DichVuBUS data=new DichVuBUS();
    ArrayList<DichVuDTO> dsdv;
    /**
     * Creates new form KhanhHang
     */
    public DSDichVu() {
        initComponents();
        dsdv=data.docDSDV();
        TaoBang();
    }
    public void TaoBang(){
        DefaultTableModel table=new DefaultTableModel();
        BangDichVu.setModel(table);
        table.addColumn("Mã Dịch Vụ");
        table.addColumn( "Tên Dịch Vụ");
        table.addColumn("Giá");
        for(DichVuDTO kh:dsdv){
            table.addRow(new Object[]{kh.getMaDichVu(),kh.getTen(),kh.getGia()});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDichVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpan = new javax.swing.JLabel();
        MaDichVu4 = new javax.swing.JLabel();
        MaDichVu5 = new javax.swing.JLabel();
        MaDichVu = new javax.swing.JTextField();
        TenDichVu = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        SuaButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 242, 197));

        BangDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BangDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangDichVu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh Sách Dịch Vụ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Thông Tin Dịch Vụ");

        jpan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jpan.setText("Mã Dịch Vụ:");
        jpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaDichVu4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaDichVu4.setText("Tên Dịch Vụ:");
        MaDichVu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaDichVu5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaDichVu5.setText("Giá:");
        MaDichVu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaDichVuActionPerformed(evt);
            }
        });

        TenDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ThemButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        SuaButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SuaButton.setText("Sửa");
        SuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MaDichVu4)
                        .addComponent(MaDichVu5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SuaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaDichVu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaDichVu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(424, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaDichVuActionPerformed

    private void BangDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangDichVuMouseClicked
        // TODO add your handling code here:
        int a=BangDichVu.getSelectedRow();
        MaDichVu.setText(BangDichVu.getValueAt(a, 0).toString());
        TenDichVu.setText(BangDichVu.getValueAt(a, 1).toString());
        SDT.setText(BangDichVu.getValueAt(a, 2).toString());
    }//GEN-LAST:event_BangDichVuMouseClicked

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        // TODO add your handling code here:
        for(DichVuDTO kh:dsdv){
            if (kh.getMaDichVu().equals(MaDichVu.getText())) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng bị trùng!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (MaDichVu.getText().length()<=10) {
                    data.them(new DichVuDTO(MaDichVu.getText(),
                                             TenDichVu.getText(),
                                             Integer.parseInt(SDT.getText())));
        }else{
            JOptionPane.showMessageDialog(this, "Mã khách hàng phải dưới 10 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        TaoBang();

    }//GEN-LAST:event_ThemButtonActionPerformed

    private void SuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButtonActionPerformed
        // TODO add your handling code here:
        String str="";
        if (BangDichVu.getSelectedRow()!=-1) {
            str=BangDichVu.getValueAt(BangDichVu.getSelectedRow(), 0).toString();
        }else{
            JOptionPane.showMessageDialog(this, "CHưa chọn khách hàng để sửa!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (MaDichVu.getText().length()<=10) {
                    data.sua(new DichVuDTO(MaDichVu.getText(),
                                             TenDichVu.getText(),
                                             Integer.parseInt(SDT.getText())));
        }else{
            JOptionPane.showMessageDialog(this, "Mã khách hàng phải dưới 10 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        TaoBang();
    }//GEN-LAST:event_SuaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDichVu;
    private javax.swing.JTextField MaDichVu;
    private javax.swing.JLabel MaDichVu4;
    private javax.swing.JLabel MaDichVu5;
    private javax.swing.JTextField SDT;
    private javax.swing.JButton SuaButton;
    private javax.swing.JTextField TenDichVu;
    private javax.swing.JButton ThemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jpan;
    // End of variables declaration//GEN-END:variables
}
