/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Phat
 */
public class HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form HoaDon
     */
    public HoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        HoaDonPanel = new javax.swing.JPanel();
        NhapTK = new javax.swing.JTextField();
        TimButton = new javax.swing.JButton();
        TitlleTKHoaDon = new javax.swing.JLabel();
        TittleChiTietHD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChiTietHoaDon = new javax.swing.JList<>();
        ButtonChinhSuaHD = new javax.swing.JButton();
        ButtonXoaHD = new javax.swing.JButton();
        ButtonXuatHD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DSHoaDon = new javax.swing.JList<>();

        HoaDonPanel.setBackground(new java.awt.Color(220, 242, 197));
        HoaDonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31), 2));
        HoaDonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HoaDonPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        HoaDonPanel.setPreferredSize(new java.awt.Dimension(1920, 860));

        NhapTK.setBackground(new java.awt.Color(220, 242, 197));
        NhapTK.setForeground(new java.awt.Color(0, 16, 31));
        NhapTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapTKActionPerformed(evt);
            }
        });

        TimButton.setBackground(new java.awt.Color(220, 242, 197));
        TimButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TimButton.setForeground(new java.awt.Color(0, 16, 31));
        TimButton.setText("Tìm");

        TitlleTKHoaDon.setBackground(new java.awt.Color(0, 16, 31));
        TitlleTKHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitlleTKHoaDon.setForeground(new java.awt.Color(0, 16, 31));
        TitlleTKHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlleTKHoaDon.setText("Tìm Kiếm Hóa Đơn");
        TitlleTKHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 16, 31))); // NOI18N

        TittleChiTietHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TittleChiTietHD.setForeground(new java.awt.Color(0, 16, 31));
        TittleChiTietHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleChiTietHD.setText("Chi Tiết Hóa Đơn");
        TittleChiTietHD.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ChiTietHoaDon.setBackground(new java.awt.Color(220, 242, 197));
        ChiTietHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31), 2));
        ChiTietHoaDon.setForeground(new java.awt.Color(0, 16, 31));
        ChiTietHoaDon.setMaximumSize(new java.awt.Dimension(50, 100));
        ChiTietHoaDon.setMinimumSize(new java.awt.Dimension(50, 100));
        ChiTietHoaDon.setPreferredSize(new java.awt.Dimension(50, 100));

        ButtonChinhSuaHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonChinhSuaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonChinhSuaHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonChinhSuaHD.setText("Chỉnh sửa hóa đơn");

        ButtonXoaHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXoaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXoaHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXoaHD.setText("Xóa hóa đơn");

        ButtonXuatHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXuatHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXuatHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXuatHD.setText("Xuất hóa đơn");
        ButtonXuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXuatHDActionPerformed(evt);
            }
        });

        DSHoaDon.setBackground(new java.awt.Color(220, 242, 197));
        DSHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31), 2));
        DSHoaDon.setForeground(new java.awt.Color(0, 16, 31));
        jScrollPane2.setViewportView(DSHoaDon);

        javax.swing.GroupLayout HoaDonPanelLayout = new javax.swing.GroupLayout(HoaDonPanel);
        HoaDonPanel.setLayout(HoaDonPanelLayout);
        HoaDonPanelLayout.setHorizontalGroup(
            HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPanelLayout.createSequentialGroup()
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(TittleChiTietHD, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(HoaDonPanelLayout.createSequentialGroup()
                                    .addComponent(NhapTK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TimButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HoaDonPanelLayout.createSequentialGroup()
                                    .addComponent(ButtonChinhSuaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                    .addComponent(ButtonXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TitlleTKHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(ButtonXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(728, Short.MAX_VALUE))
        );
        HoaDonPanelLayout.setVerticalGroup(
            HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TittleChiTietHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitlleTKHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NhapTK, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonChinhSuaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(ButtonXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HoaDonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HoaDonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void NhapTKActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void ButtonXuatHDActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonChinhSuaHD;
    private javax.swing.JButton ButtonXoaHD;
    private javax.swing.JButton ButtonXuatHD;
    private javax.swing.JList<String> ChiTietHoaDon;
    private javax.swing.JList<String> DSHoaDon;
    private javax.swing.JPanel HoaDonPanel;
    private javax.swing.JTextField NhapTK;
    private javax.swing.JButton TimButton;
    private javax.swing.JLabel TitlleTKHoaDon;
    private javax.swing.JLabel TittleChiTietHD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}
