/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.DichVu;
import DTO.HoaDonDTO;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phat
 */
public class HoaDon extends javax.swing.JPanel {
    Menu menu;
    
    /**
     * Creates new form HoaDon
     */
    public HoaDon(Menu menu) {
        initComponents();
        this.menu = menu;
        
        
        DefaultTableModel table=new DefaultTableModel();
        BangCTHD.setModel(table);
        table.addColumn("Mã Phòng");
        table.addColumn("Mã Dich Vụ");
        table.addColumn("Giá");
        BangCTHD.getTableHeader().setResizingAllowed(false);
        BangCTHD.setColumnSelectionAllowed(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HoaDonPanel = new javax.swing.JPanel();
        LabelCTHD = new javax.swing.JLabel();
        LabelTKHD = new javax.swing.JLabel();
        NgayNhan = new com.toedter.calendar.JDateChooser();
        NgayTra = new com.toedter.calendar.JDateChooser();
        NhapTimKiem = new javax.swing.JTextField();
        ButtonTim = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListTKHD = new javax.swing.JList<>();
        ButtonChinhSuaHD = new javax.swing.JButton();
        ButtonXoaHD = new javax.swing.JButton();
        ButtonXuatHD = new javax.swing.JButton();
        ButtonThemDV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangCTHD = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1720, 1080));

        HoaDonPanel.setBackground(new java.awt.Color(220, 242, 197));
        HoaDonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HoaDonPanel.setMaximumSize(new java.awt.Dimension(1720, 1080));
        HoaDonPanel.setMinimumSize(new java.awt.Dimension(1720, 1080));
        HoaDonPanel.setPreferredSize(new java.awt.Dimension(1720, 860));

        LabelCTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCTHD.setForeground(new java.awt.Color(0, 16, 31));
        LabelCTHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCTHD.setText("Chi Tiết Hóa Đơn");
        LabelCTHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 16, 31))); // NOI18N

        LabelTKHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTKHD.setForeground(new java.awt.Color(0, 16, 31));
        LabelTKHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTKHD.setText("Tìm Kiếm Hóa Đơn");
        LabelTKHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 16, 31))); // NOI18N

        NgayNhan.setMaximumSize(new java.awt.Dimension(150, 30));

        NgayTra.setMaximumSize(new java.awt.Dimension(150, 30));

        NhapTimKiem.setBackground(new java.awt.Color(220, 242, 197));
        NhapTimKiem.setForeground(new java.awt.Color(0, 16, 31));
        NhapTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31), 2));

        ButtonTim.setBackground(new java.awt.Color(220, 242, 197));
        ButtonTim.setForeground(new java.awt.Color(0, 16, 31));
        ButtonTim.setText("Tìm");

        ListTKHD.setBackground(new java.awt.Color(220, 242, 197));
        ListTKHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 16, 31)));
        jScrollPane2.setViewportView(ListTKHD);

        ButtonChinhSuaHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonChinhSuaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonChinhSuaHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonChinhSuaHD.setText("Chỉnh Sửa Hóa Đơn");

        ButtonXoaHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXoaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXoaHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXoaHD.setText("Xóa Hóa Đơn");

        ButtonXuatHD.setBackground(new java.awt.Color(220, 242, 197));
        ButtonXuatHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonXuatHD.setForeground(new java.awt.Color(0, 16, 31));
        ButtonXuatHD.setText("Xuất Hóa Đơn");

        ButtonThemDV.setBackground(new java.awt.Color(220, 242, 197));
        ButtonThemDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonThemDV.setForeground(new java.awt.Color(0, 16, 31));
        ButtonThemDV.setText("Thêm Dịch Vụ");
        ButtonThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThemDVActionPerformed(evt);
            }
        });

        BangCTHD.setBackground(new java.awt.Color(220, 242, 197));
        BangCTHD.setForeground(new java.awt.Color(0, 16, 31));
        BangCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phòng", "Mã Dịch Vụ", "Giá "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BangCTHD);
        if (BangCTHD.getColumnModel().getColumnCount() > 0) {
            BangCTHD.getColumnModel().getColumn(0).setResizable(false);
            BangCTHD.getColumnModel().getColumn(1).setResizable(false);
            BangCTHD.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout HoaDonPanelLayout = new javax.swing.GroupLayout(HoaDonPanel);
        HoaDonPanel.setLayout(HoaDonPanelLayout);
        HoaDonPanelLayout.setHorizontalGroup(
            HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPanelLayout.createSequentialGroup()
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(LabelCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HoaDonPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(LabelTKHD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonChinhSuaHD)
                            .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                                        .addComponent(NhapTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(183, 183, 183)))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        HoaDonPanelLayout.setVerticalGroup(
            HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonPanelLayout.createSequentialGroup()
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LabelTKHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HoaDonPanelLayout.createSequentialGroup()
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NhapTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonChinhSuaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(HoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HoaDonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HoaDonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThemDVActionPerformed
        // TODO add your handling code here:
        menu.addDichVu();
    }//GEN-LAST:event_ButtonThemDVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangCTHD;
    private javax.swing.JButton ButtonChinhSuaHD;
    private javax.swing.JButton ButtonThemDV;
    private javax.swing.JButton ButtonTim;
    private javax.swing.JButton ButtonXoaHD;
    private javax.swing.JButton ButtonXuatHD;
    private javax.swing.JPanel HoaDonPanel;
    private javax.swing.JLabel LabelCTHD;
    private javax.swing.JLabel LabelTKHD;
    private javax.swing.JList<String> ListTKHD;
    private com.toedter.calendar.JDateChooser NgayNhan;
    private com.toedter.calendar.JDateChooser NgayTra;
    private javax.swing.JTextField NhapTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
