/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import DTO.NguoiDung.NguoiDungDTO;
import DTO.Phong.PhongDTO;
import DTO.Phong.PhongThuongDTO;
import DTO.Phong.PhongVipDTO;

/**
 *
 * @author capij
 */
public class KhachHang extends javax.swing.JPanel {
    KhachHangBUS data=new KhachHangBUS();
    ArrayList<KhachHangDTO> dskh;
    /**
     * Creates new form KhanhHang
     */
    public KhachHang() {
        initComponents();
        dskh=data.Doc();
        TaoBang();
    }
    public void TaoBang(){
        DefaultTableModel table=new DefaultTableModel();
        BangKhachHang.setModel(table);
        table.addColumn("Mã KH");
        table.addColumn( "Họ tên");
        table.addColumn("SDT");
        table.addColumn("CCCD");
        for(KhachHangDTO kh:dskh){
            table.addRow(new Object[]{kh.getMaKhachHang(),kh.getTen(),kh.getSoDienThoai(),kh.getCCCD()});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangKhachHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TK1 = new javax.swing.JTextField();
        TK2 = new javax.swing.JTextField();
        TK3 = new javax.swing.JTextField();
        TK4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpan = new javax.swing.JLabel();
        MaKhachHang4 = new javax.swing.JLabel();
        MaKhachHang5 = new javax.swing.JLabel();
        MaKhachHang6 = new javax.swing.JLabel();
        MaKhachHang = new javax.swing.JTextField();
        TenKhachHang = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        CCCD = new javax.swing.JTextField();
        ThemButton = new javax.swing.JButton();
        SuaButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 242, 197));

        jPanel1.setBackground(new java.awt.Color(220, 242, 197));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BangKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BangKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BangKhachHang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 16, 31));
        jLabel1.setText("Danh Sách Khách Hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TK1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(TK2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(TK3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(TK4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TK4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(220, 242, 197));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 16, 31));
        jLabel2.setText("Thông Tin Khách Hàng");

        jpan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jpan.setForeground(new java.awt.Color(0, 16, 31));
        jpan.setText("Mã Khách Hàng:");
        jpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaKhachHang4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaKhachHang4.setForeground(new java.awt.Color(0, 16, 31));
        MaKhachHang4.setText("Tên Khách Hàng:");
        MaKhachHang4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaKhachHang5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaKhachHang5.setForeground(new java.awt.Color(0, 16, 31));
        MaKhachHang5.setText("Số Điện Thoại:");
        MaKhachHang5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaKhachHang6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MaKhachHang6.setForeground(new java.awt.Color(0, 16, 31));
        MaKhachHang6.setText("CCCD:");
        MaKhachHang6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKhachHangActionPerformed(evt);
            }
        });

        TenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ThemButton.setBackground(new java.awt.Color(220, 242, 197));
        ThemButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ThemButton.setForeground(new java.awt.Color(0, 16, 31));
        ThemButton.setText("Thêm");
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });

        SuaButton.setBackground(new java.awt.Color(220, 242, 197));
        SuaButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SuaButton.setForeground(new java.awt.Color(0, 16, 31));
        SuaButton.setText("Sửa");
        SuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MaKhachHang5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaKhachHang4)
                            .addComponent(MaKhachHang6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(SuaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKhachHang4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKhachHang5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKhachHang6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/CheckIn.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKhachHangActionPerformed

    private void BangKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangKhachHangMouseClicked
        // TODO add your handling code here:
        int a=BangKhachHang.getSelectedRow();
        MaKhachHang.setText(BangKhachHang.getValueAt(a, 0).toString());
        TenKhachHang.setText(BangKhachHang.getValueAt(a, 1).toString());
        SDT.setText(BangKhachHang.getValueAt(a, 2).toString());
        CCCD.setText(BangKhachHang.getValueAt(a, 3).toString());
    }//GEN-LAST:event_BangKhachHangMouseClicked

    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        // TODO add your handling code here:
        for(KhachHangDTO kh:dskh){
            if (kh.getMaKhachHang().equals(MaKhachHang.getText())) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng bị trùng!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (MaKhachHang.getText().length()<=10) {
            if (SDT.getText().length()<=12) {
                if (CCCD.getText().length()<=14) {
                    data.them(new KhachHangDTO(MaKhachHang.getText(),
                                             TenKhachHang.getText(),
                                             SDT.getText(),
                                             CCCD.getText()));
                }else{
                    JOptionPane.showMessageDialog(this, "CCCD phải dưới 14 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "SDT phải dưới 12 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Mã khách hàng phải dưới 10 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        TaoBang();

    }//GEN-LAST:event_ThemButtonActionPerformed

    private void SuaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButtonActionPerformed
        // TODO add your handling code here:
        String str="";
        if (BangKhachHang.getSelectedRow()!=-1) {
            str=BangKhachHang.getValueAt(BangKhachHang.getSelectedRow(), 0).toString();
        }else{
            JOptionPane.showMessageDialog(this, "CHưa chọn khách hàng để sửa!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (MaKhachHang.getText().length()<=10) {
            if (SDT.getText().length()<=12) {
                if (CCCD.getText().length()<=14) {
                    data.Sua(new KhachHangDTO(MaKhachHang.getText(),
                                             TenKhachHang.getText(),
                                             SDT.getText(),
                                             CCCD.getText()));
                }else{
                    JOptionPane.showMessageDialog(this, "CCCD phải dưới 14 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "SDT phải dưới 12 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Mã khách hàng phải dưới 10 kí tự!!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        TaoBang();
    }//GEN-LAST:event_SuaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangKhachHang;
    private javax.swing.JTextField CCCD;
    private javax.swing.JTextField MaKhachHang;
    private javax.swing.JLabel MaKhachHang4;
    private javax.swing.JLabel MaKhachHang5;
    private javax.swing.JLabel MaKhachHang6;
    private javax.swing.JTextField SDT;
    private javax.swing.JButton SuaButton;
    private javax.swing.JTextField TK1;
    private javax.swing.JTextField TK2;
    private javax.swing.JTextField TK3;
    private javax.swing.JTextField TK4;
    private javax.swing.JTextField TenKhachHang;
    private javax.swing.JButton ThemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jpan;
    // End of variables declaration//GEN-END:variables
}
